services:
  frontend:
     build:
      context: ./frontend 
     container_name: frontend
     volumes:
       - ./frontend:/app
     ports:
       - "5173:5173"   
     command: sh -c "npm install && npm run dev -- --host"

  backend: 
    build:
      context: ./backend 
    container_name: backend
    depends_on:
      - postgres
      - rabbitmq
      - mercure
    volumes:
      - ./backend:/app  
    expose:
      - "9000"
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@postgres:5432/mydb?serverVersion=18.1&charset=utf8"
      MESSENGER_TRANSPORT_DSN: amqp://guest:guest@rabbitmq:5672/%2f
      MERCURE_URL: http://mercure/.well-known/mercure
      MERCURE_PUBLIC_URL: http://localhost:3000/.well-known/mercure
      MERCURE_JWT_SECRET: e3jwnWMftQeXDhol76Lrk5/0BXPgUaZREm1ZRXSniVc=
    command: sh -c "
       composer install &&
      echo 'Waiting for PostgreSQL...' &&
      until php -r \"new PDO('pgsql:host=postgres;port=5432;dbname=mydb', 'myuser', 'mypassword');\"; do
        sleep 2;
      done &&
      php bin/console doctrine:migrations:migrate --no-interaction &&
      php-fpm" 

  nginx:
    image: nginx
    container_name: nginx
    depends_on: 
      - backend
      - frontend
    ports:
      - "8080:80"
    volumes:
      - ./backend:/app/backend
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf 

  postgres:
    image: postgres:18.1
    container_name: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432" 

  rabbitmq: 
    image: rabbitmq:4.2.2-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"    
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mercure:
    image: dunglas/mercure:v0.21
    container_name: mercure
    ports:
      - "3000:80"
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: 'e3jwnWMftQeXDhol76Lrk5/0BXPgUaZREm1ZRXSniVc='
      MERCURE_SUBSCRIBER_JWT_KEY: 'e3jwnWMftQeXDhol76Lrk5/0BXPgUaZREm1ZRXSniVc='
      MERCURE_JWT_SECRET: 'e3jwnWMftQeXDhol76Lrk5/0BXPgUaZREm1ZRXSniVc='
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins *
        publish_origins *
        anonymous 1
        subscriptions 1



        